services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: mini_project
  #   ports:
  #     - '8000:8000'
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #   networks:
  #     - express_network
  #   command: sh -c "npx prisma db push"

  db:
    image: postgres
    container_name: postgres_container_trial
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '7654:5432'
    networks:
      - express_network

  redis:
    image: redis
    container_name: redis_container_trial
    restart: always
    volumes:
      - redis_data:/data  # <-- Use named volume instead of local folder
    ports:
      - '6379:6379'
    networks:
      - express_network

networks:
  express_network:

volumes:
  redis_data:  # <-- Define the named volume here
  postgres_data:  # <-- Define the named volume for PostgreSQL
